name: todoist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Spartan
      fonts:
        - asset: assets/fonts/Spartan-Black.ttf
          weight: 900
        - asset: assets/fonts/Spartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/Spartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Spartan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Spartan-Light.ttf
          weight: 300
        - asset: assets/fonts/Spartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/Spartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Spartan-Thin.ttf
          weight: 100
